### ISSUE TITLE
Kernel doesn't compile.  u_f.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [montanadevelopment-archive/android_kernel_motorola_msm8937#1]
/drivers/usb/gadget/function/f_midi.c:35:10: fatal error: u_f.h: No such file or directory

You guys forgot to git add u_f.h and u_f.c from /drivers/usb/gadget/function folder or something idk.

I looked through original nougat montana motorola kernel and it seems like it contains the functions that are normally in seperate files (u_f.c and u_f.h) inside of f_midi.c; linux mainline and codeaurora msm-3.18 have those functions as u_f.c and u_f.h ,can you guys fix that issue, because I cannot compile this kernel.

Can you check for more slips like that?
I will want to use the kernel in postmarketos, and it would also be nice that in case you would "lose" the local version of the tree/kernel which contains u_f.h / u_f.c , you or someone else still had a working kernel tree.

**Comment by JarlPenguin** [comment]
@rayslash @rajatgupta1998

@kubast2 what branch?

**Comment by ghost** [comment]
Just checked and those 2 files are missing on all branches.
All of them include "u_f.h" in /drivers/usb/gadget/function/f_midi.c ,but none of them have u_f.c and u_f.h neither in /drivers/usb/gadget/function/ or anywhere else in the tree.

**Comment by kubast2** [comment]
Found the issue dude
f_midi.c import u_f.h ,but f_midi.c is in drivers/usb/gadget/function/
and u_f.h is in drivers/usb/gadget

**Comment by ghost** [comment]
Give me couple of minutes I will need to adjust the patch.

Also no idea how did you got this kernel to compile/get an zImage when the build clearly fails.

**Comment by kubast2** [comment]
#22

**Comment by JarlPenguin** [comment]
Alright. All builds work fine here, so I don't know what's happening.

**Comment by JarlPenguin** [comment]
Pull request merged; closing issue 
Cherry-picked into lineage-16.0 branch as well, those two should compile
